package com.example.dbdguide;

import java.util.Arrays;
import java.util.List;

public class MapItemData {



    // Static method to return a list of ButtonItems
    public static List<MapItem> getButtonItems() {

        return Arrays.asList(
                new MapItem("<font color='#ffffff'><b>AUTOHAVEN WRECKERS</b></font>",
                        R.drawable.maps_autohaven_wreckers_azarovs_resting_place, R.drawable.maps_autohaven_wreckers_azarovs_resting_place_preview, 1, "Autohaven Wreckers Azarovs Resting Place"),
                new MapItem("<font color='#ffffff'><b>AUTOHAVEN WRECKERS</b></font>",
                        R.drawable.maps_autohaven_wreckers_blood_lodge, R.drawable.maps_autohaven_wreckers_blood_lodge_preview, 1, "Autohaven Wreckers Blood Lodge"),
                new MapItem("<font color='#ffffff'><b>AUTOHAVEN WRECKERS</b></font>",
                        R.drawable.maps_autohaven_wreckers_gas_heaven, R.drawable.maps_autohaven_wreckers_gas_heaven_preview, 1, "Autohaven Wreckers Gas Haven"),
                new MapItem("<font color='#ffffff'><b>AUTOHAVEN WRECKERS</b></font>",
                        R.drawable.maps_autohaven_wreckers_wreckers_yard, R.drawable.maps_autohaven_wreckers_wreckers_yard_preview, 1, "Autohaven Wreckers Wreckers Yard"),
                new MapItem("<font color='#ffffff'><b>AUTOHAVEN WRECKERS</b></font>",
                        R.drawable.maps_autohaven_wreckers_wretched_shop, R.drawable.maps_autohaven_wreckers_wretched_shop_preview, 1, "Autohaven Wreckers Wretched Shop"),
                new MapItem("<font color='#ffffff'><b>BACKWATER SWAMP</b></font>",
                        R.drawable.maps_backwater_swamp_grim_pantry, R.drawable.maps_backwater_swamp_grim_pantry_preview, 6, "Backwater Swamp Grim Pantry"),
                new MapItem("<font color='#ffffff'><b>BACKWATER SWAMP</b></font>",
                        R.drawable.maps_backwater_swamp_pale_rose, R.drawable.maps_backwater_swamp_pale_rose_preview, 6, "Backwater Swamp Pale Rose"),
                new MapItem("<font color='#ffffff'><b>COLDWIND FARM</b></font>",
                        R.drawable.maps_coldwind_farm_fractured_cowshed, R.drawable.maps_coldwind_farm_fractured_cowshed_preview, 3, "Coldwind Farm Fractured Cowshed"),
                new MapItem("<font color='#ffffff'><b>COLDWIND FARM</b></font>",
                        R.drawable.maps_coldwind_farm_rancid_abattoir, R.drawable.maps_coldwind_farm_rancid_abattoir_preview, 3, "Coldwind Farm Rancid Abattoir"),
                new MapItem("<font color='#ffffff'><b>COLDWIND FARM</b></font>",
                        R.drawable.maps_coldwind_farm_rotten_fields, R.drawable.maps_coldwind_farm_rotten_fields_preview, 3, "Coldwind Farm Rotten Fields"),
                new MapItem("<font color='#ffffff'><b>COLDWIND FARM</b></font>",
                        R.drawable.maps_coldwind_farm_thompson_house, R.drawable.maps_coldwind_farm_thompson_house_preview, 3, "Coldwind Farm Thompson House"),
                new MapItem("<font color='#ffffff'><b>COLDWIND FARM</b></font>",
                        R.drawable.maps_coldwind_farm_torment_creek, R.drawable.maps_coldwind_farm_torment_creek_preview, 3, "Coldwind Farm Torment Creek"),
                new MapItem("<font color='#ffffff'><b>CROTUS PRENN ASYLUM</b></font>",
                        R.drawable.maps_crotus_prenn_asylum_disturbed_ward, R.drawable.maps_crotus_prenn_asylum_disturbed_ward_preview, 4, "Crotus Prenn Asylum Disturbed Ward"),
                new MapItem("<font color='#ffffff'><b>CROTUS PRENN ASYLUM</b></font>",
                        R.drawable.maps_crotus_prenn_asylum_father_campbells_chapel, R.drawable.maps_crotus_prenn_asylum_father_campbells_chapel_preview, 4, "Crotus Prenn Father Cambells Chapel"),
                new MapItem("<font color='#ffffff'><b>DECIMATED BORGO</b></font>",
                        R.drawable.maps_decimated_borgo_forgotten_ruins, R.drawable.maps_decimated_borgo_forgotten_ruins_preview, 23, "Decimated Borgo Forgotten Ruins"),
                new MapItem("<font color='#ffffff'><b>DECIMATED BORGO</b></font>",
                        R.drawable.maps_decimated_borgo_shattered_square, R.drawable.maps_decimated_borgo_shattered_square_preview, 19, "Decimated Borgo Shattered Square"),
                new MapItem("<font color='#ffffff'><b>DVARKA DEEPWOOD</b></font>",
                        R.drawable.maps_dvarka_deepwood_nostromo_wreckage, R.drawable.maps_dvarka_deepwood_nostromo_wreckage_preview, 21, "Dvarka Deepwood Nostromo Wreckage"),
                new MapItem("<font color='#ffffff'><b>DVARKA DEEPWOOD</b></font>",
                        R.drawable.maps_dvarka_deepwood_toba_landing, R.drawable.maps_dvarka_deepwood_toba_landing_preview, 20, "Dvarka Deepwood Toba Landing"),
                new MapItem("<font color='#ffffff'><b>FORSAKEN BONEYARD</b></font>",
                        R.drawable.maps_forsaken_boneyard_eyrie_of_crows, R.drawable.maps_forsaken_boneyard_eyrie_of_crows_preview, 17, "Forsaken Boneyard Eyrie of Crows"),
                new MapItem("<font color='#ffffff'><b>GIDEON MEAT PLANT</b></font>",
                        R.drawable.maps_gideon_meat_plant_game, R.drawable.maps_gideon_meat_plant_game_preview, 9, "Gideon Meat Plant The Game"),
                new MapItem("<font color='#ffffff'><b>GRAVE OF GLENVALE</b></font>",
                        R.drawable.maps_grave_of_glenvale_dead_dawg_saloon, R.drawable.maps_grave_of_glenvale_dead_dawg_saloon_preview, 14, "Grave of Glenvale Dead Dawg Saloon"),
                new MapItem("<font color='#ffffff'><b>HADDONFIELD</b></font>",
                        R.drawable.maps_haddonfield_lampkin_lane, R.drawable.maps_haddonfield_lampkin_lane_preview, 5, "Haddonfield Lampkin Lane"),
                new MapItem("<font color='#ffffff'><b>HAWKINS NATIONAL LABORATORY</b></font>",
                        R.drawable.maps_hawkins_national_laboratory_underground_complex, R.drawable.maps_hawkins_national_laboratory_underground_complex_preview, 12, "Hawkins National Laboratory Underground Complex"),
                new MapItem("<font color='#ffffff'><b>LÉRY'S MEMORIAL INSTITUTE</b></font>",
                        R.drawable.maps_lerys_memorial_institute_treatment_theatre, R.drawable.maps_lerys_memorial_institute_treatment_theatre_preview, 7, "Lerys Memorial Institute Treatment Theatre"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_coal_tower_1, R.drawable.maps_macmillan_estate_coal_tower_1_preview, 2, "MacMillan Estate Coal Tower 1"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_coal_tower_2, R.drawable.maps_macmillan_estate_coal_tower_2_preview, 2, "MacMillan Estate Coal Tower 2"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_groaning_storehouse_1, R.drawable.maps_macmillan_estate_groaning_storehouse_1_preview, 2, "MacMillan Estate Groaning Storehouse 1"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_groaning_storehouse_2, R.drawable.maps_macmillan_estate_groaning_storehouse_2_preview, 2, "MacMillan Estate Groaning Storehouse 2"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_ironworks_of_misery_1, R.drawable.maps_macmillan_estate_ironworks_of_misery_1_preview, 2, "MacMillan Estate Ironworks of Misery 1"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_ironworks_of_misery_2, R.drawable.maps_macmillan_estate_ironworks_of_misery_2_preview, 2, "MacMillan Estate Ironworks of Misery 2"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_shelter_woods_1, R.drawable.maps_macmillan_estate_shelter_woods_1_preview, 2, "MacMillan Estate Shelter Woods 1"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_shelter_woods_2, R.drawable.maps_macmillan_estate_shelter_woods_2_preview, 2, "MacMillan Estate Shelter Woods 2"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_suffocation_pit_1, R.drawable.maps_macmillan_estate_suffocation_pit_1_preview, 2, "MacMillan Estate Suffocation Pit 1"),
                new MapItem("<font color='#ffffff'><b>MACMILLAN ESTATE</b></font>",
                        R.drawable.maps_macmillan_estate_suffocation_pit_2, R.drawable.maps_macmillan_estate_suffocation_pit_2_preview, 2, "MacMillan Estate Suffocation Pit 2"),
                new MapItem("<font color='#ffffff'><b>ORMOND</b></font>",
                        R.drawable.maps_ormond_mount_ormond_resort_1, R.drawable.maps_ormond_mount_ormond_resort_1_preview, 10, "Ormond Mount Ormond Resort 1"),
                new MapItem("<font color='#ffffff'><b>ORMOND</b></font>",
                        R.drawable.maps_ormond_mount_ormond_resort_2, R.drawable.maps_ormond_mount_ormond_resort_2_preview, 10, "Ormond Mount Ormond Resort 2"),
                new MapItem("<font color='#ffffff'><b>ORMOND</b></font>",
                        R.drawable.maps_ormond_mount_ormond_resort_3, R.drawable.maps_ormond_mount_ormond_resort_3_preview, 10, "Ormond Mount Ormond Resort 3"),
                new MapItem("<font color='#ffffff'><b>ORMOND</b></font>",
                        R.drawable.maps_ormond_mount_ormond_resort_1, R.drawable.maps_ormond_ormond_lake_mine_preview, 24, "Ormond Ormond Lake Mine"),
                new MapItem("<font color='#ffffff'><b>RACCOON CITY</b></font>",
                        R.drawable.maps_raccoon_city_raccoon_city_police_station_east_wing, R.drawable.maps_raccoon_city_raccoon_city_police_station_east_wing_preview, 16, "RPD Raccoon City Police Station East Wing"),
                new MapItem("<font color='#ffffff'><b>RACCOON CITY</b></font>",
                        R.drawable.maps_raccoon_city_raccoon_city_police_station_west_wing, R.drawable.maps_raccoon_city_raccoon_city_police_station_west_wing_preview, 16, "RPD Raccoon City Police Station West Wing"),
                new MapItem("<font color='#ffffff'><b>RED FOREST</b></font>",
                        R.drawable.maps_red_forest_mothers_dwelling, R.drawable.maps_red_forest_mothers_dwelling_preview, 11, "Red Forest Mothers Dwelling"),
                new MapItem("<font color='#ffffff'><b>RED FOREST</b></font>",
                        R.drawable.maps_red_forest_temple_of_purgation, R.drawable.maps_red_forest_temple_of_purgation_preview, 11, "Red Forest Temple of Purgation"),
                new MapItem("<font color='#ffffff'><b>SILENT HILL</b></font>",
                        R.drawable.maps_silent_hill_midwich_elementary_school, R.drawable.maps_silent_hill_midwich_elementary_school_preview, 15, "Silent Hill Midwich Elementary School"),
                new MapItem("<font color='#ffffff'><b>SPRINGWOOD</b></font>",
                        R.drawable.maps_springwood_badham_preschool_1, R.drawable.maps_springwood_badham_preschool_1_preview, 8, "Springwood Badham Preschool 1"),
                new MapItem("<font color='#ffffff'><b>SPRINGWOOD</b></font>",
                        R.drawable.maps_springwood_badham_preschool_2, R.drawable.maps_springwood_badham_preschool_2_preview, 8, "Springwood Badham Preschool 2"),
                new MapItem("<font color='#ffffff'><b>SPRINGWOOD</b></font>",
                        R.drawable.maps_springwood_badham_preschool_3, R.drawable.maps_springwood_badham_preschool_3_preview, 8, "Springwood Badham Preschool 3"),
                new MapItem("<font color='#ffffff'><b>SPRINGWOOD</b></font>",
                        R.drawable.maps_springwood_badham_preschool_4, R.drawable.maps_springwood_badham_preschool_4_preview, 8, "Springwood Badham Preschool 4"),
                new MapItem("<font color='#ffffff'><b>SPRINGWOOD</b></font>",
                        R.drawable.maps_springwood_badham_preschool_5, R.drawable.maps_springwood_badham_preschool_5_preview, 8, "Springwood Badham Preschool 5"),
                new MapItem("<font color='#ffffff'><b>WITHERED ISLE</b></font>",
                        R.drawable.maps_withered_isle_garden_of_joy, R.drawable.maps_withered_isle_garden_of_joy_preview, 18, "Withered Isle Garden of Joy"),
                new MapItem("<font color='#ffffff'><b>WITHERED ISLE</b></font>",
                        R.drawable.maps_withered_isle_greenville_square, R.drawable.maps_withered_isle_greenville_square_preview, 22, "Withered Isle Greenville Square"),
                new MapItem("<font color='#ffffff'><b>YAMAOKA ESTATE</b></font>",
                        R.drawable.maps_yamaoka_estate_family_residence_1, R.drawable.maps_yamaoka_estate_family_residence_1_preview, 13, "Yamaoka Estate Family Residence 1"),
                new MapItem("<font color='#ffffff'><b>YAMAOKA ESTATE</b></font>",
                        R.drawable.maps_yamaoka_estate_family_residence_2, R.drawable.maps_yamaoka_estate_family_residence_2_preview, 13, "Yamaoka Estate Family Residence 2"),
                new MapItem("<font color='#ffffff'><b>YAMAOKA ESTATE</b></font>",
                        R.drawable.maps_yamaoka_estate_sanctum_of_wrath_1, R.drawable.maps_yamaoka_estate_sanctum_of_wrath_1_preview, 13, "Yamaoka Estate Sanctum of Wrath 1"),
                new MapItem("<font color='#ffffff'><b>YAMAOKA ESTATE</b></font>",
                        R.drawable.maps_yamaoka_estate_sanctum_of_wrath_2, R.drawable.maps_yamaoka_estate_sanctum_of_wrath_2_preview, 13, "Yamaoka Estate Sanctum of Wrath 2")
        );
    }
}